export const languageNames: Record<string, string> = {
  ko: '한국어',
  en: 'English',
  'zh-Hans': '简体中文',
  th: 'ภาษาไทย',
  ru: 'Русский',
  ne: 'नेपाली',
};
const labels = {
  ko: [
    '본문으로 바로가기',
    '홈',
    '참고 자료',
    '궁금한 점을 확인하세요',
    '이 페이지에서',
    '함께 보면 좋은 안내',
    '전화 문의',
    '한국어 홈페이지',
    '네이버 지도',
    '새 창',
  ],
  en: [
    'Skip to content',
    'Home',
    'References',
    'Questions and answers',
    'On this page',
    'Related information',
    'Call the clinic',
    'Korean website',
    'Naver map',
    'new window',
  ],
  'zh-Hans': [
    '跳转到正文',
    '首页',
    '参考资料',
    '问答',
    '本页内容',
    '相关信息',
    '致电诊所',
    '韩语网站',
    'Naver地图',
    '新窗口',
  ],
  th: [
    'ข้ามไปยังเนื้อหา',
    'หน้าแรก',
    'แหล่งข้อมูล',
    'คำถามและคำตอบ',
    'เนื้อหาในหน้านี้',
    'ข้อมูลที่เกี่ยวข้อง',
    'โทรคลินิก',
    'เว็บไซต์ภาษาเกาหลี',
    'แผนที่ Naver',
    'หน้าต่างใหม่',
  ],
  ru: [
    'Перейти к содержимому',
    'Главная',
    'Источники',
    'Вопросы и ответы',
    'На этой странице',
    'Связанная информация',
    'Позвонить в клинику',
    'Сайт на корейском',
    'Карта Naver',
    'новое окно',
  ],
  ne: [
    'मुख्य सामग्रीमा जानुहोस्',
    'गृहपृष्ठ',
    'स्रोतहरू',
    'प्रश्न र उत्तर',
    'यस पृष्ठमा',
    'सम्बन्धित जानकारी',
    'क्लिनिकमा फोन गर्नुहोस्',
    'कोरियाली वेबसाइट',
    'Naver नक्सा',
    'नयाँ विन्डो',
  ],
};
export function pageLabels(language = 'ko') {
  const [skip, home, sources, questions, contents, related, call, koreanSite, map, newWindow] =
    labels[language as keyof typeof labels] ?? labels.ko;
  return { skip, home, sources, questions, contents, related, call, koreanSite, map, newWindow };
}
